<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" file="unittest/loader.py" name="unittest.loader._FailedTest-20191030131607" skipped="0" tests="1" time="0.022" timestamp="2019-10-30T13:16:07">
	<testcase classname="unittest.loader._FailedTest" file="/usr/lib/python3.6/unittest/loader.py" line="33" name="app_tests" time="0.022" timestamp="2019-10-30T13:16:07">
		<error message="Failed to import test module: app_tests
Traceback (most recent call last):
  File &quot;/usr/lib/python3.6/unittest/loader.py&quot;, line 153, in loadTestsFromName
    module = __import__(module_name)
  File &quot;/home/ashok/pybuild-flow/src/unittest/python/app_tests.py&quot;, line 6, in &lt;module&gt;
    from src.main.python.app import flask_jenkins_app
ModuleNotFoundError: No module named 'src'
" type="ImportError">
<![CDATA[ImportError: Failed to import test module: app_tests
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/ashok/pybuild-flow/src/unittest/python/app_tests.py", line 6, in <module>
    from src.main.python.app import flask_jenkins_app
ModuleNotFoundError: No module named 'src'

]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
